# Generated by Django 2.1.7 on 2019-04-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_cost_price', models.FloatField()),
                ('cust_clear_free', models.FloatField()),
                ('one_tenthous_cost', models.FloatField()),
                ('retail_cost', models.FloatField()),
                ('hot_sell_degree', models.CharField(max_length=10)),
                ('buy_difficulty', models.CharField(max_length=10)),
                ('activite_product_list', models.TextField()),
                ('customer_message', models.TextField()),
                ('product_hk_info', models.TextField()),
                ('dutyfree_storeprice', models.FloatField()),
                ('hot_sell_product', models.TextField()),
                ('findpro_help', models.TextField()),
            ],
        ),
    ]
