# Generated by Django 2.1.7 on 2019-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activite_product_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='buy_difficulty',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_clear_free',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dutyfree_storeprice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='findpro_help',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hot_sell_degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hot_sell_product',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='one_tenthous_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='product_hk_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='retail_cost',
            field=models.FloatField(null=True),
        ),
    ]
